<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no">

<title>Error</title>

<link rel="stylesheet" type="text/css" href="<?php p(BASE_PATH) ?>view/error.css" />
<link rel="shortcut icon" type="image/x-icon" href="<?php p(BASE_PATH) ?>view/favicon.ico" />

</head>
<body>

<main>
    <h1><img src="<?php p(BASE_PATH) ?>view/logo-invert.svg" alt="Spirit" width="70" /> This journal doesn&rsquo;t exist!</h1>
    <p>Don&rsquo;t worry, just head back to the <a href="<?php p(BASE_PATH) ?>">homepage</a>.</p>
</main>

</body>
</html>
