<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">
<title><?php p($journal['name']) ?></title>

<link rel="stylesheet" type="text/css" href="<?php p(BASE_PATH) ?>view/journal.css" />
<link rel="shortcut icon" type="image/x-icon" href="<?php p(BASE_PATH) ?>view/favicon.ico" />

<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
<script type="text/javascript" src="<?php p(BASE_PATH) ?>view/color-thief.js"></script>
<script type="text/javascript" src="<?php p(BASE_PATH) ?>view/journal.js"></script>

</head>
<body>

<h1><?php p($journal['name']) ?></h1>

<nav>
    <h2>Journals</h2>

    <p>
        <a href="https://github.com/yishn/Spirit" title="Powered by Spirit">
            <img src="<?php p(BASE_PATH) ?>view/logo-invert.svg" alt="Spirit" width="40" />
        </a>
    </p>

    <ol>
        <?php foreach ($journals as $j): ?>
            <?php if ($j['id'] == $journal['id']): ?>
                <li class="current">
                    <a href="<?php p($j['permalink']) ?>"><?php p($j['name']) ?></a>

                    <?php if (isset($journal['start_date'])): ?>
                        <time datetime="<?php p($journal['start_date']->format('Y-m-d')) ?>">
                            from <em><?php p($journal['start_date']->format('Y-m-d')) ?></em>
                        </time>
                        <time datetime="<?php p($journal['end_date']->format('Y-m-d')) ?>">
                            to <em><?php p($journal['end_date']->format('Y-m-d')) ?></em>
                        </time>
                    <?php endif ?>
                </li>
            <?php else: ?>
                <li>
                    <a href="<?php p($j['permalink']) ?>"><?php p($j['name']) ?></a>
                </li>
            <?php endif ?>
        <?php endforeach ?>
    </ol>
</nav>

<main>
    <h2>Photos</h2>

    <?php foreach ($journal['photos'] as $photo): ?>
        <article id="<?php p($photo['id']) ?>">
            <section class="image">
                <img src="<?php p($photo['src']) ?>" />

                <ul>
                    <a href="#<?php p($photo['id']) ?>" title="Permalink">
                        <?php if (isset($photo['date'])): ?>
                            <time datetime="<?php p($photo['date']->format('Y-m-d H:i:s')) ?>">
                                <?php echo $photo['date']->format('jS F Y, H:i') ?>
                            </time>
                        <?php else: ?>
                            &para;
                        <?php endif ?>
                    </a>
                    <?php if (ALLOW_DOWNLOAD): ?>
                        <a href="<?php p($photo['download']) ?>" title="Download">
                            &#11015;
                        </a>
                    <?php endif ?>
                </ul>
            </section>
            <?php if (isset($photo['description'])): ?>
                <aside>
                    <?php echo $photo['description'] ?>
                </aside>
            <?php endif ?>
        </article>
    <?php endforeach ?>
</main>

</body>
</html>
