<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">
<title><?php p($journal['name']) ?></title>
<link rel="stylesheet" type="text/css" href="<?php p(BASE_PATH) ?>view/spirit.css" />
<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
<script type="text/javascript" src="<?php p(BASE_PATH) ?>view/journal.js"></script>

</head>
<body>

<h1><?php p($journal['name']) ?></h1>

<nav>
    <h2>Journals</h2>

    <ol>
        <?php foreach ($journals as $j): ?>
            <?php if ($j['id'] == $journal['id']): ?>
                <li class="current">
                    <a href="<?php p($j['permalink']) ?>"><?php p($j['name']) ?></a>

                    <time datetime="<?php p($journal['start_date']->format('Y-m-d')) ?>">
                        from <em><?php p($journal['start_date']->format('Y-m-d')) ?></em>
                    </time>
                    <time datetime="<?php p($journal['end_date']->format('Y-m-d')) ?>">
                        to <em><?php p($journal['end_date']->format('Y-m-d')) ?></em>
                    </time>
                </li>
            <?php else: ?>
                <li>
                    <a href="<?php p($j['permalink']) ?>"><?php p($j['name']) ?></a>
                </li>
            <?php endif ?>
        <?php endforeach ?>
    </ol>
</nav>

<main>
    <h2>Photos</h2>

    <?php foreach ($journal['photos'] as $photo): ?>
        <article id="<?php p($photo['id']) ?>">
            <p class="image">
                <img src="<?php p($photo['src']) ?>" />

                <a href="#<?php p($photo['id']) ?>" title="Permalink">
                <?php if (isset($photo['date'])): ?>
                    <time datetime="<?php p($photo['date']->format('Y-m-d H:i:s')) ?>">
                        <?php p($photo['date']->format('jS F Y')) ?>
                    </time>
                <?php else: ?>
                    #
                <?php endif ?>
                </a>
            </p>
            <?php if (isset($photo['description'])): ?>
                <aside>
                    <?php echo $photo['description'] ?>
                </aside>
            <?php endif ?>
        </article>
    <?php endforeach ?>
</main>

</body>
</html>
